dfz:
  outputs:
    dev:
      account: dqpppxv-jp80110
      database: DB_DBT_POC
      password: Welcome@123
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 4
      type: snowflake
      user: saikrishna
      warehouse: COMPUTE_WH
  target: dev