dfz:
  outputs:
    dev:
      account: ylbwfsa-if35636
      database: DB_DBT_POC
      password: Rama@003
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 4
      type: snowflake
      user: ANKITHA
      warehouse: COMPUTE_WH
  target: dev