dfz:
  outputs:
    dev:
      account: ivcjvew-sv34964
      database: DB_DBT_POC
      password: Nandini@123
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 4
      type: snowflake
      user: NANDINI
      warehouse: COMPUTE_WH
  target: dev